// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectWeb.Data;

#nullable disable

namespace ProjectWeb.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241111032012_SeedingBooKTable")]
    partial class SeedingBooKTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectWeb.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Greenwich",
                            CategoryId = 1,
                            Description = "Basic C",
                            Price = 0.0,
                            Title = "C Programming"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Who knows",
                            CategoryId = 1,
                            Description = "ok",
                            Price = 0.0,
                            Title = "Robinhood"
                        },
                        new
                        {
                            Id = 3,
                            Author = "FPT",
                            CategoryId = 3,
                            Description = "Hard",
                            Price = 0.0,
                            Title = "Data Structures"
                        },
                        new
                        {
                            Id = 4,
                            Author = "StudyGuys",
                            CategoryId = 3,
                            Description = "Ok",
                            Price = 0.0,
                            Title = ".NET advanced"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Greenwich",
                            CategoryId = 2,
                            Description = "You have to learn it",
                            Price = 0.0,
                            Title = "Application Development"
                        });
                });

            modelBuilder.Entity("ProjectWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayPriority")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Give you a feel of challenge",
                            DisplayPriority = 1,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 2,
                            Description = "So romantique",
                            DisplayPriority = 4,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 3,
                            Description = "So scary",
                            DisplayPriority = 3,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 4,
                            Description = "So interesting",
                            DisplayPriority = 2,
                            Name = "Scifi"
                        });
                });

            modelBuilder.Entity("ProjectWeb.Models.Book", b =>
                {
                    b.HasOne("ProjectWeb.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
